name: NodeJS with Gulp

on:
  push:
    branches: [ "(/boot)" ]
  pull_request:
    branches: [ "(/boot)" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
    - name: Build
      run: |
        npm install webpack
        webpack
